"""add_missing_automation_schedule_fields

Revision ID: 28c56bdf8e7b
Revises: c9010d6ef9ab
Create Date: 2025-10-28 05:10:33.756007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28c56bdf8e7b'
down_revision: Union[str, None] = 'c9010d6ef9ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('automation_schedules', sa.Column('config', sa.Text(), nullable=True))
    op.add_column('automation_schedules', sa.Column('minute_of_hour', sa.Integer(), nullable=True))
    op.add_column('automation_schedules', sa.Column('last_error_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('automation_schedules', 'last_error_at')
    op.drop_column('automation_schedules', 'minute_of_hour')
    op.drop_column('automation_schedules', 'config')
    # ### end Alembic commands ###
