"""Add missing fields to businesses table

Revision ID: 4b0924498819
Revises: a1608ce71239
Create Date: 2025-10-21 10:23:13.713842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b0924498819'
down_revision: Union[str, None] = 'a1608ce71239'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('size', sa.String(length=50), nullable=True))
    op.add_column('businesses', sa.Column('contact_email', sa.String(length=255), nullable=True))
    op.add_column('businesses', sa.Column('contact_phone', sa.String(length=50), nullable=True))
    op.add_column('businesses', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('businesses', sa.Column('subscription_status', sa.String(length=50), nullable=True))
    op.add_column('businesses', sa.Column('trial_ends_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'trial_ends_at')
    op.drop_column('businesses', 'subscription_status')
    op.drop_column('businesses', 'address')
    op.drop_column('businesses', 'contact_phone')
    op.drop_column('businesses', 'contact_email')
    op.drop_column('businesses', 'size')
    # ### end Alembic commands ###
