"""Add circuit breaker and API request logging

Revision ID: 73dd10da5165
Revises: 28c56bdf8e7b
Create Date: 2025-10-28 14:21:09.143048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73dd10da5165'
down_revision: Union[str, None] = '28c56bdf8e7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circuit_breakers',
    sa.Column('id', sa.CHAR(36), nullable=False),
    sa.Column('business_id', sa.CHAR(36), nullable=False),
    sa.Column('api_config_id', sa.CHAR(36), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('state', sa.Enum('CLOSED', 'OPEN', 'HALF_OPEN', name='circuitbreakerstate'), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('consecutive_successes', sa.Integer(), nullable=False),
    sa.Column('failure_threshold', sa.Integer(), nullable=False),
    sa.Column('success_threshold', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('last_failure_at', sa.DateTime(), nullable=True),
    sa.Column('last_failure_reason', sa.Text(), nullable=True),
    sa.Column('last_failure_type', sa.String(length=100), nullable=True),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('half_opened_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('manually_disabled', sa.Boolean(), nullable=False),
    sa.Column('disabled_reason', sa.Text(), nullable=True),
    sa.Column('disabled_by_user_id', sa.Integer(), nullable=True),
    sa.Column('disabled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['api_config_id'], ['api_configs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['disabled_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_circuit_breakers_api_config_id'), 'circuit_breakers', ['api_config_id'], unique=True)
    op.create_index(op.f('ix_circuit_breakers_business_id'), 'circuit_breakers', ['business_id'], unique=False)
    op.create_index(op.f('ix_circuit_breakers_last_failure_at'), 'circuit_breakers', ['last_failure_at'], unique=False)
    op.create_index(op.f('ix_circuit_breakers_provider'), 'circuit_breakers', ['provider'], unique=False)
    op.create_index(op.f('ix_circuit_breakers_state'), 'circuit_breakers', ['state'], unique=False)
    op.create_table('api_request_logs',
    sa.Column('id', sa.CHAR(36), nullable=False),
    sa.Column('business_id', sa.CHAR(36), nullable=False),
    sa.Column('api_config_id', sa.CHAR(36), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('client_id', sa.CHAR(36), nullable=True),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('job_run_id', sa.CHAR(36), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('response_time_ms', sa.Float(), nullable=True),
    sa.Column('results_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_type', sa.String(length=100), nullable=True),
    sa.Column('rate_limit_remaining', sa.Integer(), nullable=True),
    sa.Column('rate_limit_reset', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['api_config_id'], ['api_configs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_run_id'], ['job_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_request_logs_api_config_id'), 'api_request_logs', ['api_config_id'], unique=False)
    op.create_index(op.f('ix_api_request_logs_business_id'), 'api_request_logs', ['business_id'], unique=False)
    op.create_index(op.f('ix_api_request_logs_client_id'), 'api_request_logs', ['client_id'], unique=False)
    op.create_index(op.f('ix_api_request_logs_created_at'), 'api_request_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_api_request_logs_error_type'), 'api_request_logs', ['error_type'], unique=False)
    op.create_index(op.f('ix_api_request_logs_job_run_id'), 'api_request_logs', ['job_run_id'], unique=False)
    op.create_index(op.f('ix_api_request_logs_provider'), 'api_request_logs', ['provider'], unique=False)
    op.create_index(op.f('ix_api_request_logs_success'), 'api_request_logs', ['success'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_request_logs_success'), table_name='api_request_logs')
    op.drop_index(op.f('ix_api_request_logs_provider'), table_name='api_request_logs')
    op.drop_index(op.f('ix_api_request_logs_job_run_id'), table_name='api_request_logs')
    op.drop_index(op.f('ix_api_request_logs_error_type'), table_name='api_request_logs')
    op.drop_index(op.f('ix_api_request_logs_created_at'), table_name='api_request_logs')
    op.drop_index(op.f('ix_api_request_logs_client_id'), table_name='api_request_logs')
    op.drop_index(op.f('ix_api_request_logs_business_id'), table_name='api_request_logs')
    op.drop_index(op.f('ix_api_request_logs_api_config_id'), table_name='api_request_logs')
    op.drop_table('api_request_logs')
    op.drop_index(op.f('ix_circuit_breakers_state'), table_name='circuit_breakers')
    op.drop_index(op.f('ix_circuit_breakers_provider'), table_name='circuit_breakers')
    op.drop_index(op.f('ix_circuit_breakers_last_failure_at'), table_name='circuit_breakers')
    op.drop_index(op.f('ix_circuit_breakers_business_id'), table_name='circuit_breakers')
    op.drop_index(op.f('ix_circuit_breakers_api_config_id'), table_name='circuit_breakers')
    op.drop_table('circuit_breakers')
    # ### end Alembic commands ###
