"""Initial database with UUIDs and multi-tenancy

Revision ID: a1608ce71239
Revises:
Create Date: 2025-10-19 14:54:27.355192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.models.business import GUID


# revision identifiers, used by Alembic.
revision: str = 'a1608ce71239'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('tier', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('api_key_hash', sa.String(length=255), nullable=True),
    sa.Column('sso_enabled', sa.Boolean(), nullable=False),
    sa.Column('sso_provider', sa.String(length=50), nullable=True),
    sa.Column('sso_config', sa.Text(), nullable=True),
    sa.Column('sso_domain', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_businesses_domain'), 'businesses', ['domain'], unique=False)
    op.create_index(op.f('ix_businesses_id'), 'businesses', ['id'], unique=False)
    op.create_index(op.f('ix_businesses_is_active'), 'businesses', ['is_active'], unique=False)
    op.create_index(op.f('ix_businesses_name'), 'businesses', ['name'], unique=True)
    op.create_table('job_runs',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('job_id', sa.String(length=100), nullable=False),
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('events_found', sa.Integer(), nullable=False),
    sa.Column('events_new', sa.Integer(), nullable=False),
    sa.Column('clients_processed', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('job_metadata', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_runs_id'), 'job_runs', ['id'], unique=False)
    op.create_index(op.f('ix_job_runs_job_id'), 'job_runs', ['job_id'], unique=True)
    op.create_index(op.f('ix_job_runs_job_type'), 'job_runs', ['job_type'], unique=False)
    op.create_index(op.f('ix_job_runs_started_at'), 'job_runs', ['started_at'], unique=False)
    op.create_table('search_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_hash', sa.String(length=64), nullable=False),
    sa.Column('query_text', sa.String(length=500), nullable=False),
    sa.Column('results_json', sa.Text(), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('cached_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_search_cache_lookup', 'search_cache', ['query_hash', 'cached_at'], unique=False)
    op.create_index(op.f('ix_search_cache_query_hash'), 'search_cache', ['query_hash'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('SYSTEM_ADMIN', 'BUSINESS_ADMIN', 'BASE_USER', name='userrole'), nullable=False),
    sa.Column('business_id', GUID(), nullable=True),
    sa.Column('sso_enabled', sa.Boolean(), nullable=False),
    sa.Column('sso_provider', sa.String(length=50), nullable=True),
    sa.Column('last_password_change', sa.DateTime(), nullable=True),
    sa.Column('password_reset_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_business_id'), 'users', ['business_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('business_id', GUID(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('old_values', sa.Text(), nullable=True),
    sa.Column('new_values', sa.Text(), nullable=True),
    sa.Column('changed_fields', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_action_created', 'audit_logs', ['action', 'created_at'], unique=False)
    op.create_index('ix_audit_business_created', 'audit_logs', ['business_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_business_id'), 'audit_logs', ['business_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_record_id'), 'audit_logs', ['record_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_table_name'), 'audit_logs', ['table_name'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index('ix_audit_table_record', 'audit_logs', ['table_name', 'record_id'], unique=False)
    op.create_index('ix_audit_user_created', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_table('clients',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('business_id', GUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('domain', sa.String(length=200), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('company_size', sa.String(length=50), nullable=True),
    sa.Column('revenue_range', sa.String(length=50), nullable=True),
    sa.Column('headquarters_location', sa.String(length=200), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('search_keywords', sa.Text(), nullable=True),
    sa.Column('monitoring_frequency', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_to_user_id', sa.Integer(), nullable=True),
    sa.Column('tier', sa.String(length=50), nullable=True),
    sa.Column('health_score', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_assigned_to_user_id'), 'clients', ['assigned_to_user_id'], unique=False)
    op.create_index('ix_clients_business_active', 'clients', ['business_id', 'is_active'], unique=False)
    op.create_index('ix_clients_business_deleted', 'clients', ['business_id', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_clients_business_id'), 'clients', ['business_id'], unique=False)
    op.create_index(op.f('ix_clients_domain'), 'clients', ['domain'], unique=False)
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_index(op.f('ix_clients_is_active'), 'clients', ['is_active'], unique=False)
    op.create_index(op.f('ix_clients_is_deleted'), 'clients', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=False)
    op.create_table('tags',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('business_id', GUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_business_id'), 'tags', ['business_id'], unique=False)
    op.create_index('ix_tags_business_name', 'tags', ['business_id', 'name'], unique=True)
    op.create_table('client_tags',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('client_id', GUID(), nullable=False),
    sa.Column('tag_id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_tags_client_id'), 'client_tags', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_tags_tag_id'), 'client_tags', ['tag_id'], unique=False)
    op.create_index('ix_client_tags_unique', 'client_tags', ['client_id', 'tag_id'], unique=True)
    op.create_table('events',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('business_id', GUID(), nullable=False),
    sa.Column('client_id', GUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('subcategory', sa.String(length=50), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('duplicate_of_event_id', GUID(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_starred', sa.Boolean(), nullable=False),
    sa.Column('user_notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['duplicate_of_event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_business_category', 'events', ['business_id', 'category'], unique=False)
    op.create_index('ix_events_business_client', 'events', ['business_id', 'client_id'], unique=False)
    op.create_index('ix_events_business_date', 'events', ['business_id', 'event_date'], unique=False)
    op.create_index('ix_events_business_deleted', 'events', ['business_id', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_events_business_id'), 'events', ['business_id'], unique=False)
    op.create_index(op.f('ix_events_category'), 'events', ['category'], unique=False)
    op.create_index(op.f('ix_events_client_id'), 'events', ['client_id'], unique=False)
    op.create_index(op.f('ix_events_content_hash'), 'events', ['content_hash'], unique=False)
    op.create_index(op.f('ix_events_event_date'), 'events', ['event_date'], unique=False)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_events_is_deleted'), 'events', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_events_relevance_score'), 'events', ['relevance_score'], unique=False)
    op.create_table('event_tags',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('event_id', GUID(), nullable=False),
    sa.Column('tag_id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_tags_event_id'), 'event_tags', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_tags_tag_id'), 'event_tags', ['tag_id'], unique=False)
    op.create_index('ix_event_tags_unique', 'event_tags', ['event_id', 'tag_id'], unique=True)
    op.create_table('event_user_interactions',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('event_id', GUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('is_starred', sa.Boolean(), nullable=False),
    sa.Column('starred_at', sa.DateTime(), nullable=True),
    sa.Column('user_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_user_interactions_event_id'), 'event_user_interactions', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_user_interactions_user_id'), 'event_user_interactions', ['user_id'], unique=False)
    op.create_index('ix_event_user_unique', 'event_user_interactions', ['event_id', 'user_id'], unique=True)
    op.create_table('notifications',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('business_id', GUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('link_url', sa.String(length=500), nullable=True),
    sa.Column('related_event_id', GUID(), nullable=True),
    sa.Column('related_client_id', GUID(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_business_created', 'notifications', ['business_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_notifications_business_id'), 'notifications', ['business_id'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index('ix_notifications_user_created', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_unread', 'notifications', ['user_id', 'is_read'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notifications_user_unread', table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index('ix_notifications_user_created', table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_business_id'), table_name='notifications')
    op.drop_index('ix_notifications_business_created', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_event_user_unique', table_name='event_user_interactions')
    op.drop_index(op.f('ix_event_user_interactions_user_id'), table_name='event_user_interactions')
    op.drop_index(op.f('ix_event_user_interactions_event_id'), table_name='event_user_interactions')
    op.drop_table('event_user_interactions')
    op.drop_index('ix_event_tags_unique', table_name='event_tags')
    op.drop_index(op.f('ix_event_tags_tag_id'), table_name='event_tags')
    op.drop_index(op.f('ix_event_tags_event_id'), table_name='event_tags')
    op.drop_table('event_tags')
    op.drop_index(op.f('ix_events_relevance_score'), table_name='events')
    op.drop_index(op.f('ix_events_is_deleted'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_date'), table_name='events')
    op.drop_index(op.f('ix_events_content_hash'), table_name='events')
    op.drop_index(op.f('ix_events_client_id'), table_name='events')
    op.drop_index(op.f('ix_events_category'), table_name='events')
    op.drop_index(op.f('ix_events_business_id'), table_name='events')
    op.drop_index('ix_events_business_deleted', table_name='events')
    op.drop_index('ix_events_business_date', table_name='events')
    op.drop_index('ix_events_business_client', table_name='events')
    op.drop_index('ix_events_business_category', table_name='events')
    op.drop_table('events')
    op.drop_index('ix_client_tags_unique', table_name='client_tags')
    op.drop_index(op.f('ix_client_tags_tag_id'), table_name='client_tags')
    op.drop_index(op.f('ix_client_tags_client_id'), table_name='client_tags')
    op.drop_table('client_tags')
    op.drop_index('ix_tags_business_name', table_name='tags')
    op.drop_index(op.f('ix_tags_business_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_clients_name'), table_name='clients')
    op.drop_index(op.f('ix_clients_is_deleted'), table_name='clients')
    op.drop_index(op.f('ix_clients_is_active'), table_name='clients')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_domain'), table_name='clients')
    op.drop_index(op.f('ix_clients_business_id'), table_name='clients')
    op.drop_index('ix_clients_business_deleted', table_name='clients')
    op.drop_index('ix_clients_business_active', table_name='clients')
    op.drop_index(op.f('ix_clients_assigned_to_user_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_index('ix_audit_user_created', table_name='audit_logs')
    op.drop_index('ix_audit_table_record', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_table_name'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_record_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_business_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index('ix_audit_business_created', table_name='audit_logs')
    op.drop_index('ix_audit_action_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_business_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_search_cache_query_hash'), table_name='search_cache')
    op.drop_index('ix_search_cache_lookup', table_name='search_cache')
    op.drop_table('search_cache')
    op.drop_index(op.f('ix_job_runs_started_at'), table_name='job_runs')
    op.drop_index(op.f('ix_job_runs_job_type'), table_name='job_runs')
    op.drop_index(op.f('ix_job_runs_job_id'), table_name='job_runs')
    op.drop_index(op.f('ix_job_runs_id'), table_name='job_runs')
    op.drop_table('job_runs')
    op.drop_index(op.f('ix_businesses_name'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_is_active'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_id'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_domain'), table_name='businesses')
    op.drop_table('businesses')
    # ### end Alembic commands ###
