"""add_automation_tables_user_preferences_event_raw_data_schedules_email_logs

Revision ID: c9010d6ef9ab
Revises: 42_cleanup_orphaned
Create Date: 2025-10-27 17:24:08.851787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.models.business import GUID


# revision identifiers, used by Alembic.
revision: str = 'c9010d6ef9ab'
down_revision: Union[str, None] = '42_cleanup_orphaned'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_schedules',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('business_id', GUID(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('client_ids', sa.Text(), nullable=True),
    sa.Column('schedule_type', sa.String(length=20), nullable=False),
    sa.Column('cron_expression', sa.String(length=100), nullable=True),
    sa.Column('hour_of_day', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_status', sa.String(length=20), nullable=True),
    sa.Column('last_run_job_id', GUID(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_run_job_id'], ['job_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_automation_schedules_business_active', 'automation_schedules', ['business_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_automation_schedules_business_id'), 'automation_schedules', ['business_id'], unique=False)
    op.create_index('ix_automation_schedules_business_type', 'automation_schedules', ['business_id', 'job_type'], unique=False)
    op.create_index(op.f('ix_automation_schedules_created_by_user_id'), 'automation_schedules', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_automation_schedules_id'), 'automation_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_automation_schedules_is_active'), 'automation_schedules', ['is_active'], unique=False)
    op.create_index(op.f('ix_automation_schedules_job_type'), 'automation_schedules', ['job_type'], unique=False)
    op.create_index('ix_automation_schedules_next_run', 'automation_schedules', ['is_active', 'next_run_at'], unique=False)
    op.create_index(op.f('ix_automation_schedules_next_run_at'), 'automation_schedules', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_automation_schedules_schedule_type'), 'automation_schedules', ['schedule_type'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('business_id', GUID(), nullable=False),
    sa.Column('notification_enabled', sa.Boolean(), nullable=False),
    sa.Column('email_notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('relevance_threshold', sa.Float(), nullable=False),
    sa.Column('notification_categories', sa.Text(), nullable=True),
    sa.Column('notification_frequency', sa.String(length=20), nullable=False),
    sa.Column('assigned_clients_only', sa.Boolean(), nullable=False),
    sa.Column('digest_time', sa.Time(), nullable=True),
    sa.Column('digest_day_of_week', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_preferences_business_id'), 'user_preferences', ['business_id'], unique=False)
    op.create_index(op.f('ix_user_preferences_id'), 'user_preferences', ['id'], unique=False)
    op.create_index('ix_user_preferences_user_business', 'user_preferences', ['user_id', 'business_id'], unique=False)
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=True)
    op.create_table('email_logs',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('business_id', GUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', GUID(), nullable=True),
    sa.Column('job_run_id', GUID(), nullable=True),
    sa.Column('email_type', sa.String(length=50), nullable=False),
    sa.Column('recipient_email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body_preview', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('clicked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_run_id'], ['job_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_logs_business_id'), 'email_logs', ['business_id'], unique=False)
    op.create_index('ix_email_logs_business_type', 'email_logs', ['business_id', 'email_type'], unique=False)
    op.create_index('ix_email_logs_business_user', 'email_logs', ['business_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_email_logs_email_type'), 'email_logs', ['email_type'], unique=False)
    op.create_index(op.f('ix_email_logs_event_id'), 'email_logs', ['event_id'], unique=False)
    op.create_index(op.f('ix_email_logs_id'), 'email_logs', ['id'], unique=False)
    op.create_index(op.f('ix_email_logs_sent_at'), 'email_logs', ['sent_at'], unique=False)
    op.create_index(op.f('ix_email_logs_status'), 'email_logs', ['status'], unique=False)
    op.create_index('ix_email_logs_status_sent', 'email_logs', ['status', 'sent_at'], unique=False)
    op.create_index(op.f('ix_email_logs_user_id'), 'email_logs', ['user_id'], unique=False)
    op.create_index('ix_email_logs_user_sent', 'email_logs', ['user_id', 'sent_at'], unique=False)
    op.create_table('event_raw_data',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('business_id', GUID(), nullable=False),
    sa.Column('client_id', GUID(), nullable=False),
    sa.Column('job_run_id', GUID(), nullable=True),
    sa.Column('source_api', sa.String(length=50), nullable=False),
    sa.Column('search_query', sa.String(length=500), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('processed_into_event_id', GUID(), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_run_id'], ['job_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['processed_into_event_id'], ['events.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_raw_data_business_client', 'event_raw_data', ['business_id', 'client_id'], unique=False)
    op.create_index(op.f('ix_event_raw_data_business_id'), 'event_raw_data', ['business_id'], unique=False)
    op.create_index('ix_event_raw_data_business_processed', 'event_raw_data', ['business_id', 'is_processed'], unique=False)
    op.create_index(op.f('ix_event_raw_data_client_id'), 'event_raw_data', ['client_id'], unique=False)
    op.create_index(op.f('ix_event_raw_data_content_hash'), 'event_raw_data', ['content_hash'], unique=False)
    op.create_index(op.f('ix_event_raw_data_created_at'), 'event_raw_data', ['created_at'], unique=False)
    op.create_index(op.f('ix_event_raw_data_id'), 'event_raw_data', ['id'], unique=False)
    op.create_index(op.f('ix_event_raw_data_is_processed'), 'event_raw_data', ['is_processed'], unique=False)
    op.create_index(op.f('ix_event_raw_data_job_run_id'), 'event_raw_data', ['job_run_id'], unique=False)
    op.create_index(op.f('ix_event_raw_data_source_api'), 'event_raw_data', ['source_api'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_raw_data_source_api'), table_name='event_raw_data')
    op.drop_index(op.f('ix_event_raw_data_job_run_id'), table_name='event_raw_data')
    op.drop_index(op.f('ix_event_raw_data_is_processed'), table_name='event_raw_data')
    op.drop_index(op.f('ix_event_raw_data_id'), table_name='event_raw_data')
    op.drop_index(op.f('ix_event_raw_data_created_at'), table_name='event_raw_data')
    op.drop_index(op.f('ix_event_raw_data_content_hash'), table_name='event_raw_data')
    op.drop_index(op.f('ix_event_raw_data_client_id'), table_name='event_raw_data')
    op.drop_index('ix_event_raw_data_business_processed', table_name='event_raw_data')
    op.drop_index(op.f('ix_event_raw_data_business_id'), table_name='event_raw_data')
    op.drop_index('ix_event_raw_data_business_client', table_name='event_raw_data')
    op.drop_table('event_raw_data')
    op.drop_index('ix_email_logs_user_sent', table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_user_id'), table_name='email_logs')
    op.drop_index('ix_email_logs_status_sent', table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_status'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_sent_at'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_id'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_event_id'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_email_type'), table_name='email_logs')
    op.drop_index('ix_email_logs_business_user', table_name='email_logs')
    op.drop_index('ix_email_logs_business_type', table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_business_id'), table_name='email_logs')
    op.drop_table('email_logs')
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_index('ix_user_preferences_user_business', table_name='user_preferences')
    op.drop_index(op.f('ix_user_preferences_id'), table_name='user_preferences')
    op.drop_index(op.f('ix_user_preferences_business_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_automation_schedules_schedule_type'), table_name='automation_schedules')
    op.drop_index(op.f('ix_automation_schedules_next_run_at'), table_name='automation_schedules')
    op.drop_index('ix_automation_schedules_next_run', table_name='automation_schedules')
    op.drop_index(op.f('ix_automation_schedules_job_type'), table_name='automation_schedules')
    op.drop_index(op.f('ix_automation_schedules_is_active'), table_name='automation_schedules')
    op.drop_index(op.f('ix_automation_schedules_id'), table_name='automation_schedules')
    op.drop_index(op.f('ix_automation_schedules_created_by_user_id'), table_name='automation_schedules')
    op.drop_index('ix_automation_schedules_business_type', table_name='automation_schedules')
    op.drop_index(op.f('ix_automation_schedules_business_id'), table_name='automation_schedules')
    op.drop_index('ix_automation_schedules_business_active', table_name='automation_schedules')
    op.drop_table('automation_schedules')
    # ### end Alembic commands ###
