"""add_api_configs_table

Revision ID: d734723ed3b2
Revises: 4b0924498819
Create Date: 2025-10-27 08:57:12.162830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.models.business import GUID


# revision identifiers, used by Alembic.
revision: str = 'd734723ed3b2'
down_revision: Union[str, None] = '4b0924498819'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_configs',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('business_id', GUID(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('provider_name', sa.String(length=200), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=True),
    sa.Column('api_secret', sa.Text(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('config_data', sa.Text(), nullable=True),
    sa.Column('max_tokens_per_month', sa.Integer(), nullable=True),
    sa.Column('tokens_used_current_month', sa.Integer(), nullable=True),
    sa.Column('last_reset_date', sa.DateTime(), nullable=True),
    sa.Column('rate_limit_per_hour', sa.Integer(), nullable=True),
    sa.Column('requests_this_hour', sa.Integer(), nullable=True),
    sa.Column('last_request_time', sa.DateTime(), nullable=True),
    sa.Column('cost_per_1k_tokens', sa.Float(), nullable=True),
    sa.Column('estimated_monthly_cost', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_tested_at', sa.DateTime(), nullable=True),
    sa.Column('last_test_status', sa.String(length=50), nullable=True),
    sa.Column('last_test_message', sa.Text(), nullable=True),
    sa.Column('config_file_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_user_id', GUID(), nullable=True),
    sa.Column('updated_by_user_id', GUID(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_configs_business_id'), 'api_configs', ['business_id'], unique=False)
    op.create_index(op.f('ix_api_configs_id'), 'api_configs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_configs_id'), table_name='api_configs')
    op.drop_index(op.f('ix_api_configs_business_id'), table_name='api_configs')
    op.drop_table('api_configs')
    # ### end Alembic commands ###
